version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
  payment-service:
    build: ./payment-service
    ports:
      - "5000:5000"
  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
